### PR TITLE
Updated API key to version 4.79.1 and incremented version number to 1.2.11

### PR DESCRIPTION
**Pull request by Kyrtap5**

### CODE REVIEW

**Comment by nborrmann** [comment]
Could you also bump the version in setup.py? So it gets published to pypi. Thanks!

**Comment by Kyrtap5** [comment]
Sure! The newer version number is now also included in this request. 🙂

**Comment by nborrmann** [comment]
Thanks!

**Comment by workedbeforepush** [comment]
Hello, is there any chance that you can explain how to extract the api key from the .so file?

**Comment by petrekova** [comment]
@WakaToa take a look at issue #40

**Pull request merged**
